//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v12.3.0.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using Sdk.Fu.ProviderContracts;

namespace Sdk.Fu
{
    #pragma warning disable

    

    #pragma warning restore
}