name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build Api solution
      run: dotnet build dotnet-oas.Api.sln --configuration Release
    - name: Build Sdk solution
      run: dotnet build dotnet-oas.Sdk.sln --configuration Release
